apiVersion: v1
kind: Deployment  
metadata:
  name: Monitor-server-deployment
  labels:
    app: monitor-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: monitor-server
  spec:
    containers:
    - name: ping-monitor
      image: kodekloud/examplevotingapp_vote:v1
      imagepullPolicy: IfNotPresent
      ports:
        - containerPort: 5000
      resources:
        limits:
          memory: "256Mi"
          cpu: "500m"    
        requests:
          memory: "128Mi"
          cpu: "250m"  