---
apiVersion: v1
kind: Service
metadata:
  name: ping-monitor-service
spec:
  type: NodePort
  selector:
    app: ping-monitor  # Esto le indica al servicio a qué pods debe enviar el tráfico
  ports:
    - port: 5000       # El puerto dentro del clúster
      targetPort: 5000 # El puerto donde escucha tu app de Flask en el contenedor
      nodePort: 32000  # El puerto físico que se abrirá en tu servidor para entrar desde el navegador
