---
apiVersion: v1
kind: Service
metadata:
  name: ping-monitor-service
  labels:
    app: monitor-server
spec:
  type: ClusterIP
  selector:
    app: monitor-server
  ports:
    - name: http
      port: 5000
      targetPort: 5000
